const Hindi={
"Help!":["बचाओ!","aag"],
"Jump.":	["उछलो,कूदो,छलांग"],
"Hello":["नमस्ते,नमस्ते"],
"Cheers":["वाह-वाह!"],	
"Understand":["समझे"],
"No":["नहीं"],
"I":["मैं"],
"A lot":["बहुत"],
"Perfect":["उत्तम"],
"Forgot":["भूल"],
"Forget":["भूलना"],
"Dog":["कुत्ते"],
"Inside":["अंदर"],
"Outside":["बाहर"],
"Welcome":["स्वागतम्"],
"Fun":["मज़े"],
"Answer":["जवाब"],
"Birds":["पंछी"],
"Fly":["उड़ना"],
"Alright":["ठीक"],
"Know":["मालूम"],
"Forgive":["माफ़"],
"Laugh":["हँसना"],
"Try":["कोशिश"],
"Sing":["गाना"],
"Fire":["आग"],
"Burn":["जलना"],
"Mathematics":["गणित"],
"Math":["गणित"],
"Maths":["गणित"],
"Love":["प्यार"],
"House":["घर"],
"Home":["घर"],
"Buy":["खरीदना "],
"History":["इतिहास"]
}
export default Hindi